<?php
/**
 * Expected WordPress Gutenberg Block Render Callback
 * Generated by Ra-Ai2WP-Engine v1.1.0
 * Strict adherence to WPCS 3.4.1 (WordPress Coding Standards)
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

function rtw_render_hero_banner_block( $attributes, $content ) {
    $headline     = isset( $attributes['headline'] ) ? sanitize_text_field( $attributes['headline'] ) : esc_html__( 'توسعه نسل آینده وردپرس با هوش مصنوعی', 'rtw' );
    $subheading   = isset( $attributes['subheading'] ) ? sanitize_text_field( $attributes['subheading'] ) : esc_html__( 'تبدیل آنی کامپوننت‌های مدرن ری‌اکت به بلاک‌های بومی گوتنبرگ با رعایت WPCS 3.4.1', 'rtw' );
    $cta_url      = isset( $attributes['callToActionUrl'] ) ? esc_url( $attributes['callToActionUrl'] ) : 'https://github.com/Aqamirrazavi/Ra-Ai2WP-Engine';
    $block_id     = isset( $attributes['blockId'] ) ? sanitize_html_class( $attributes['blockId'] ) : 'rtw-hero-01';

    ob_start();
    ?>
    <section id="<?php echo esc_attr( $block_id ); ?>" class="rtw-hero-container bg-slate-900 text-white p-8 rounded-2xl shadow-xl">
        <div class="max-w-4xl mx-auto text-center">
            <h1 class="text-4xl font-extrabold tracking-tight mb-4 text-cyan-400">
                <?php echo esc_html( $headline ); ?>
            </h1>
            <p class="text-lg text-slate-300 mb-6">
                <?php echo esc_html( $subheading ); ?>
            </p>
            <div class="flex justify-center gap-4">
                <a href="<?php echo esc_url( $cta_url ); ?>" class="px-6 py-3 bg-cyan-500 hover:bg-cyan-600 font-bold rounded-lg transition" target="_blank" rel="noopener noreferrer">
                    <?php esc_html_e( 'مشاهده در گیت‌هاب', 'rtw' ); ?>
                </a>
            </div>
        </div>
    </section>
    <?php
    return ob_get_clean();
}
